### ISSUE TITLE
Graphenes are not matched correctly using \X

### ISSUE THREAD

**Issue by thallgren** [jruby/joni#30]
Testing the letter à in the form of a graphene encoded as U+0061 U+0300 using a Ruby MRI (2.3.1 here but version doesn't matter), a \X will match the graphene:
```
$ irb
2.3.1 :001 > x = "h\u0061\u0300llo"
 => "hàllo" 
2.3.1 :002 > x =~ /h\Xllo/
 => 0 
```
The match fails when testing the same thing using JRuby:
```
$ irb
jruby-9.1.7.0 :001 > x = "h\u0061\u0300llo"
 => "hàllo"
jruby-9.1.7.0 :002 > x =~ /h\Xllo/
 => nil 
```

**Comment by lopex** [comment]
Fixed in https://github.com/jruby/joni/commit/b00c05c829633f364a54da3ca2e4c3f189aca1fa
