### ISSUE TITLE
Expose Syntax fields to allow copying a modifying an existing Syntax

### ISSUE THREAD

**Issue by nezda** [jruby/joni#48]
In order to support making a modified `Syntax` from an existing one it would be nice if these fields were accessible (e.g., `public final`)
https://github.com/jruby/joni/blob/master/src/org/joni/Syntax.java#L28-L31

**Comment by headius** [comment]
If that's all, I don't have any problem with it. Normally I'd prefer to put them behind an accessor method, but clearly that's not the pattern this class is using. 🙄

**Comment by headius** [comment]
Released as 2.1.39.

**Comment by nezda** [comment]
Totally safe too since primitives - thank you!
