### ISSUE TITLE
Support for specifying \G position

### ISSUE THREAD

**Issue by henry-thompson** [jruby/joni#49]
In Onigmo, it is possible to specify the position of `\G` by calling the function [`onig_search_gpos`](https://github.com/k-takata/Onigmo/blob/a06a42b51713eeafe30a939827031c3ba79da936/regexec.c#L3794). I have implemented this functionality in my fork [here](https://github.com/henry-thompson/joni/commit/66ac96535ef2dd38d36f785ccdae0e29613c780e).

If you think this could be a useful addition for Joni as well, I'm very happy to PR it in—happy to make any modifications beforehand as well, please just let me know.

I'm not sure what API you would want, but for now I have implemented it as overloaded implementations of `Matcher#search` and `Matcher#searchInterruptible`:

`search(int gpos, int start, int range, int option)` and `searchInterruptible(int gpos, int start, int range, int option)`.

Thanks!

**Comment by lopex** [comment]
Yeah, we miss that functionality right now, so if it's a direct port of Onigmo functionality we're happy to merge

**Comment by headius** [comment]
Not a high priority but we would be very grateful for a port of the related logic!

**Comment by henry-thompson** [comment]
@lopex @headius thanks for the replies, I've opened the PR above to implement this feature.

**Comment by lopex** [comment]
Thank you!
