### ISSUE TITLE
Enable GitHub Discussions

### ISSUE THREAD

**Issue by nezda** [jruby/joni#69]
GitHub Discussions provides a transparent place to discuss things that don't make as much sense directly as issues. For example:
* what version of [Oniguruma](https://github.com/kkos/oniguruma) / [Onigmo](https://github.com/k-takata/Onigmo) is joni up-to-date with?
    * should I make issue requesting particular upstream fixes / features?, e.g.,
       * I'd really like `(?L)` and related fixes (https://github.com/kkos/oniguruma/commit/923f518a1cde3ee9cea0a37d4bbaa42414c6778c, https://github.com/kkos/oniguruma/commit/b9da4848f00cad6cb0d6cc0157dafebe9e896de6, etc.)
       * fix for https://github.com/kkos/oniguruma/issues/284 would be nice

... but Onigmo hasn't been updated for quite a while. Can this version (used by jruby) include a superset of Ruby features (and fixes)?

* Q & A / how do I X?
* [djl](https://github.com/deepjavalibrary/djl/discussions) includes a "Show and tell" area which could be cool. (I'm curious which high profile libraries and systems use joni!)

**Comment by enebo** [comment]
started it up.  This is a great idea.
